### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by SlipCord** [vuongle2609/Manga-Web#4]
how did you add manga there if there is no admin panel, and how did you register if there is no database, please tell me, I wanted to study it all because I really like your site

**Comment by SlipCord** [comment]
how did you add manga there if there is no admin panel, and how did you register if there is no database, please tell me, I wanted to study it all because I really like your site

**Comment by vuongle2609** [comment]
Glad you like it!!. 
- About manga, I didn't add it by myself, I'm using NodeJS for crawling data from another website. You can find out about it here: https://github.com/vuongle2609/truyentranh-manga-API.
- About users database, I'm setting the repo to private so you can't see it. But i'm using Mongodb and Nodejs for it.
If you want to make a website like me, you can use mangadex API : https://api.mangadex.org/swagger.html. I use it for my newest manga project https://github.com/vuongle2609/Manga-Web-Next but notice about cors issues, you will need a proxy or something to bypass cors. That's all, good luck.

**Comment by vuongle2609** [comment]
> how did you add manga there if there is no admin panel, and how did you register if there is no database, please tell me, I wanted to study it all because I really like your site

Glad you like it!!.

- About manga, I didn't add it by myself, I'm using NodeJS for crawling data from another website. You can find out about it here: https://github.com/vuongle2609/truyentranh-manga-API.
- About users database, I'm setting the repo to private so you can't see it. But i'm using Mongodb and Nodejs for it.
If you want to make a website like me, you can use mangadex API : https://api.mangadex.org/swagger.html. I use it for my newest manga project https://github.com/vuongle2609/Manga-Web-Next but notice about cors issues, you will need a proxy or something to bypass cors. That's all, good luck.

**Comment by SlipCord** [comment]
there is no connection mongodb

**Comment by SlipCord** [comment]
i ran your script on npm run

**Comment by vuongle2609** [comment]
> there is no connection mongodb

https://github.com/vuongle2609/manga-user My repo for users database, you have to create a MongoDB by yourself 😊.

**Comment by SlipCord** [comment]
where to enter a token from mongodb?
![image](https://user-images.githubusercontent.com/73776330/174490344-48a91949-6eb9-4a67-86f6-19994c67b34c.png)

**Comment by vuongle2609** [comment]
> where to enter a token from mongodb? ![image](https://user-images.githubusercontent.com/73776330/174490344-48a91949-6eb9-4a67-86f6-19994c67b34c.png)

https://mongoosejs.com/docs/connections.html 
You can read it from here!
